services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: ghostnet-container
    environment:
      POSTGRES_USER: ghostnet
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ghostnet-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: ghostnet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ghostnet.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "8080:80"  # Access pgAdmin at http://localhost:8080
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin data


  ghostnet-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghostnet-app
    ports:
      - "8070:8080" # Map app's server port
    depends_on:
      - postgres
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: ghostnet
      DB_PASSWORD: test
      DB_URL: jdbc:postgresql://localhost:5432/postgres

volumes:
  postgres_data:
  pgadmin_data:

